config-version: 2

name: 'recharge_integration_tests'
version: '1.5.0'

profile: 'integration_tests' 

models:
  +persist_docs:
    relation: true
    columns: "{{ false if target.type in ('databricks') else true }}"
  +schema: "recharge_{{ var('directed_schema','dev') }}"  ## To be used for validation tests

vars:
  # recharge__checkout_enabled: true # @docs-include
  recharge:
    recharge_schema: recharge_integration_tests
    recharge_address_identifier: "address_data"
    recharge_address_discounts_identifier: "address_discounts_data"
    recharge_address_shipping_line_identifier: "address_shipping_line_data"
    recharge_charge_identifier: "charge_data"
    recharge_charge_discount_identifier: "charge_discount_data"
    recharge_charge_line_item_identifier: "charge_line_item_data" 
    recharge_charge_order_attribute_identifier: "charge_order_attribute_data"
    recharge_charge_shipping_line_identifier: "charge_shipping_line_data"
    recharge_charge_tax_line_identifier: "charge_tax_line_data"
    recharge_checkout_identifier: "checkout_data"
    recharge_customer_identifier: "customer_data"
    recharge_discount_identifier: "discount_data"
    recharge_one_time_product_identifier: "one_time_product_data"
    recharge_orders_identifier: "orders_data"
    recharge_order_line_item_identifier: "order_line_item_data"
    recharge_subscription_identifier: "subscription_data"
    recharge_subscription_history_identifier: "subscription_history_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  +docs:
    show: False
  +quote_columns: "{{ target.type == 'redshift' or var('fivetran_using_source_casing', false) }}"
  recharge_integration_tests:
    address_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        company: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        created_at: "timestamp"
        updated_at: "timestamp"
        _fivetran_synced: "timestamp"

    address_discounts_data:
      +column_types:
        address_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: "timestamp"

    address_shipping_line_data:
      +column_types:
        address_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: "timestamp"

    charge_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        address_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: "timestamp"
        updated_at: "timestamp"
        processed_at: "timestamp"
        scheduled_at: "timestamp"
        subtotal_price: "float"
        total_price: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        last_charge_attempt_date: "timestamp"
        retry_date: "timestamp"
        _fivetran_synced: "timestamp"

    charge_discount_data:
      +column_types:
        charge_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        value: "float"
        _fivetran_synced: "timestamp"

    charge_line_item_data:
      +column_types:
        charge_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_product_id_ecommerce: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_variant_id_ecommerce: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        total_price: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        _fivetran_synced: "timestamp"

    charge_order_attribute_data:
      +column_types:
        charge_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: "timestamp"

    charge_shipping_line_data:
      +column_types:
        charge_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: "timestamp"

    charge_tax_line_data:
      +column_types:
        charge_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: "timestamp"

    checkout_data:
      +column_types:
        completed_at: "timestamp"
        created_at: "timestamp"
        updated_at: "timestamp"
        subtotal_price: "float"
        total_price: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"

    customer_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: "timestamp"
        updated_at: "timestamp"
        first_charge_processed_at: "timestamp"
        _fivetran_synced: "timestamp"

    discount_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        starts_at: "timestamp"
        ends_at: "timestamp"
        created_at: "timestamp"
        updated_at: "timestamp"
        applies_to_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: "timestamp"

    one_time_product_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        address_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: "timestamp"
        updated_at: "timestamp"
        next_charge_scheduled_at: "timestamp"
        price: "float"
        external_product_id_ecommerce: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_variant_id_ecommerce: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: "timestamp"

    orders_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        address_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        charge_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: "timestamp"
        updated_at: "timestamp"
        processed_at: "timestamp"
        scheduled_at: "timestamp"
        shipped_date: "timestamp"
        total_price: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        is_prepaid: boolean
        _fivetran_synced: "timestamp"

    order_bool_int_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        address_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        charge_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: "timestamp"
        updated_at: "timestamp"
        processed_at: "timestamp"
        scheduled_at: "timestamp"
        shipped_date: "timestamp"
        total_price: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        is_prepaid: boolean
        _fivetran_synced: "timestamp"

    order_line_item_data:
      +column_types:
        order_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_product_id_ecommerce: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_variant_id_ecommerce: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        total_price: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        _fivetran_synced: "timestamp"

    subscription_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        address_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: "timestamp"
        updated_at: "timestamp"
        cancelled_at: "timestamp"
        next_charge_scheduled_at: "timestamp"
        price: "float"
        external_product_id_ecommerce: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_variant_id_ecommerce: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: "timestamp"

    subscription_history_data:
      +column_types:
        subscription_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        updated_at: "timestamp"
        address_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: "timestamp"
        cancelled_at: "timestamp"
        next_charge_scheduled_at: "timestamp"
        price: "float"
        external_product_id_ecommerce: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_variant_id_ecommerce: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: "timestamp"
flags:
  send_anonymous_usage_stats: False
  use_colors: True
