config-version: 2

name: 'recharge_integration_tests'
version: '0.1.0'

profile: 'integration_tests' 

vars:
  recharge_source:
    recharge_schema: recharge_integration_tests_02
    recharge_address_identifier: "address_data"
    recharge_address_shipping_line_identifier: "address_shipping_line_data"
    recharge_charge_identifier: "charge_data"
    recharge_charge_discount_code_identifier: "charge_discount_code_data"
    recharge_charge_line_item_identifier: "charge_line_item_data"
    recharge_charge_note_attribute_identifier: "charge_note_attribute_data"
    recharge_charge_shipping_line_identifier: "charge_shipping_line_data"
    recharge_charge_tax_line_identifier: "charge_tax_line_data"
    recharge_customer_identifier: "customer_data"
    recharge_discount_identifier: "discount_data"
    recharge_one_time_product_identifier: "one_time_product_data"
    order: "{{ ref('order_data') }}" # Comment out for generating docs -- Uncomment this before sending to buildkite.
    # recharge_order_identifier: "order_data" # Uncomment for generating docs -- Comment this out before sending to buildkite.
    recharge_order_line_item_identifier: "order_line_item_data"
    recharge_payment_method_identifier: "payment_method_data"
    recharge_plan_identifier: "plan_data"
    recharge_subscription_identifier: "subscription_data"
    recharge_subscription_history_identifier: "subscription_history_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  recharge_integration_tests:
    +column_types:
      _FIVETRAN_SYNCED: "timestamp"
      CANCELLED_AT: "timestamp"
      CREATED_AT: "timestamp"
      PROCESSED_AT: "timestamp"
      NEXT_CHARGE_SCHEDULED_AT: "timestamp"
      SCHEDULED_AT: "timestamp"
      SUBTOTAL_PRICE: "float"
      TOTAL_PRICE: "float"
      UPDATED_AT: "timestamp"
      ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      ADDRESS_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      CHARGE_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      CUSTOMER_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      DISCOUNT_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      SHOPIFY_PRODUCT_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      SHOPIFY_VARIANT_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      SUBSCRIPTION_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    charge_data:
      +column_types:
        LAST_CHARGE_ATTEMPT_DATE: "timestamp"
        RETRY_DATE: "timestamp"
    charge_line_item_data:
      +column_types:
        PROPERTY_BUNDLE_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        PROPERTY_WIDGET_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    customer_data:
      +column_types:
        FIRST_CHARGE_PROCESSED_AT: "timestamp"
    discount_data:
      +column_types:
        APPLIES_TO_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ENDS_AT: "timestamp"
        STARTS_AT: "timestamp"
    order_data:
      +column_types:
        SHIPPED_DATE: "timestamp"
        SHIPPING_DATE: "timestamp"

dispatch: 
  - macro_namespace: dbt_utils 
    search_order: ['spark_utils', 'dbt_utils'] 
