config-version: 2

name: 'recharge_integration_tests'
version: '1.1.0'

profile: 'integration_tests' 

models:
  +schema: "recharge_{{ var('directed_schema','dev') }}"  ## To be used for validation tests

vars:
  # recharge__checkout_enabled: true # @docs-include
  recharge:
    recharge_schema: recharge_integration_tests_03
    recharge_address_identifier: "address_data"
    recharge_address_discounts_identifier: "address_discounts_data"
    recharge_address_shipping_line_identifier: "address_shipping_line_data"
    recharge_charge_identifier: "charge_data"
    recharge_charge_discount_identifier: "charge_discount_data"
    recharge_charge_line_item_identifier: "charge_line_item_data" 
    recharge_charge_order_attribute_identifier: "charge_order_attribute_data"
    recharge_charge_shipping_line_identifier: "charge_shipping_line_data"
    recharge_charge_tax_line_identifier: "charge_tax_line_data"
    recharge_checkout_identifier: "checkout_data"
    recharge_customer_identifier: "customer_data"
    recharge_discount_identifier: "discount_data"
    recharge_one_time_product_identifier: "one_time_product_data"
    recharge_orders_identifier: "orders_data"
    recharge_order_line_item_identifier: "order_line_item_data"
    recharge_subscription_identifier: "subscription_data"
    recharge_subscription_history_identifier: "subscription_history_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  +docs:
    show: False
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  recharge_integration_tests:
    address_data:
      +column_types:
        ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CUSTOMER_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        COMPANY: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        CREATED_AT: "timestamp"
        UPDATED_AT: "timestamp"
        _FIVETRAN_SYNCED: "timestamp"

    address_discounts_data:
      +column_types:
        ADDRESS_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _FIVETRAN_SYNCED: "timestamp"

    address_shipping_line_data:
      +column_types:
        ADDRESS_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _FIVETRAN_SYNCED: "timestamp"

    charge_data:
      +column_types:
        ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ADDRESS_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CUSTOMER_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CREATED_AT: "timestamp"
        UPDATED_AT: "timestamp"
        PROCESSED_AT: "timestamp"
        SCHEDULED_AT: "timestamp"
        SUBTOTAL_PRICE: "float"
        TOTAL_PRICE: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        LAST_CHARGE_ATTEMPT_DATE: "timestamp"
        RETRY_DATE: "timestamp"
        _FIVETRAN_SYNCED: "timestamp"

    charge_discount_data:
      +column_types:
        CHARGE_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        VALUE: "float"
        _FIVETRAN_SYNCED: "timestamp"

    charge_line_item_data:
      +column_types:
        CHARGE_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        EXTERNAL_PRODUCT_ID_ECOMMERCE: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        EXTERNAL_VARIANT_ID_ECOMMERCE: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        TOTAL_PRICE: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        _FIVETRAN_SYNCED: "timestamp"

    charge_order_attribute_data:
      +column_types:
        CHARGE_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _FIVETRAN_SYNCED: "timestamp"

    charge_shipping_line_data:
      +column_types:
        CHARGE_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _FIVETRAN_SYNCED: "timestamp"

    charge_tax_line_data:
      +column_types:
        CHARGE_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _FIVETRAN_SYNCED: "timestamp"

    checkout_data:
      +column_types:
        COMPLETED_AT: "timestamp"
        CREATED_AT: "timestamp"
        UPDATED_AT: "timestamp"
        SUBTOTAL_PRICE: "float"
        TOTAL_PRICE: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"

    customer_data:
      +column_types:
        ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CREATED_AT: "timestamp"
        UPDATED_AT: "timestamp"
        FIRST_CHARGE_PROCESSED_AT: "timestamp"
        _FIVETRAN_SYNCED: "timestamp"

    discount_data:
      +column_types:
        ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        STARTS_AT: "timestamp"
        ENDS_AT: "timestamp"
        CREATED_AT: "timestamp"
        UPDATED_AT: "timestamp"
        APPLIES_TO_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _FIVETRAN_SYNCED: "timestamp"

    one_time_product_data:
      +column_types:
        ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ADDRESS_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CUSTOMER_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CREATED_AT: "timestamp"
        UPDATED_AT: "timestamp"
        NEXT_CHARGE_SCHEDULED_AT: "timestamp"
        PRICE: "float"
        EXTERNAL_PRODUCT_ID_ECOMMERCE: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        EXTERNAL_VARIANT_ID_ECOMMERCE: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _FIVETRAN_SYNCED: "timestamp"

    orders_data:
      +column_types:
        ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CUSTOMER_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ADDRESS_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CHARGE_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CREATED_AT: "timestamp"
        UPDATED_AT: "timestamp"
        PROCESSED_AT: "timestamp"
        SCHEDULED_AT: "timestamp"
        SHIPPED_DATE: "timestamp"
        TOTAL_PRICE: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        IS_PREPAID: boolean
        _FIVETRAN_SYNCED: "timestamp"

    order_bool_int_data:
      +column_types:
        ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CUSTOMER_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ADDRESS_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CHARGE_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CREATED_AT: "timestamp"
        UPDATED_AT: "timestamp"
        PROCESSED_AT: "timestamp"
        SCHEDULED_AT: "timestamp"
        SHIPPED_DATE: "timestamp"
        TOTAL_PRICE: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        IS_PREPAID: boolean
        _FIVETRAN_SYNCED: "timestamp"

    order_line_item_data:
      +column_types:
        ORDER_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        EXTERNAL_PRODUCT_ID_ECOMMERCE: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        EXTERNAL_VARIANT_ID_ECOMMERCE: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        TOTAL_PRICE: "{{ 'string' if target.name in ['bigquery', 'spark', 'databricks'] else 'varchar' }}"
        _FIVETRAN_SYNCED: "timestamp"

    subscription_data:
      +column_types:
        ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ADDRESS_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CUSTOMER_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CREATED_AT: "timestamp"
        UPDATED_AT: "timestamp"
        CANCELLED_AT: "timestamp"
        NEXT_CHARGE_SCHEDULED_AT: "timestamp"
        PRICE: "float"
        EXTERNAL_PRODUCT_ID_ECOMMERCE: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        EXTERNAL_VARIANT_ID_ECOMMERCE: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _FIVETRAN_SYNCED: "timestamp"

    subscription_history_data:
      +column_types:
        SUBSCRIPTION_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        UPDATED_AT: "timestamp"
        ADDRESS_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CUSTOMER_ID: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        CREATED_AT: "timestamp"
        CANCELLED_AT: "timestamp"
        NEXT_CHARGE_SCHEDULED_AT: "timestamp"
        PRICE: "float"
        EXTERNAL_PRODUCT_ID_ECOMMERCE: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        EXTERNAL_VARIANT_ID_ECOMMERCE: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        _FIVETRAN_SYNCED: "timestamp"
flags:
  send_anonymous_usage_stats: False
  use_colors: True